// Generated by Supabase CLI — regenerate with: npx supabase gen types typescript --local
// DO NOT EDIT MANUALLY

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          email: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          email: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          email?: string
          created_at?: string
          updated_at?: string
        }
      }
      workspaces: {
        Row: {
          id: string
          name: string
          slug: string
          logo_url: string | null
          plan: 'free' | 'starter' | 'pro' | 'enterprise'
          owner_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          logo_url?: string | null
          plan?: 'free' | 'starter' | 'pro' | 'enterprise'
          owner_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          logo_url?: string | null
          plan?: 'free' | 'starter' | 'pro' | 'enterprise'
          owner_id?: string
          created_at?: string
          updated_at?: string
        }
      }
      workspace_members: {
        Row: {
          id: string
          workspace_id: string
          user_id: string
          role: 'owner' | 'admin' | 'member' | 'viewer'
          invited_by: string | null
          joined_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          user_id: string
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          invited_by?: string | null
          joined_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          user_id?: string
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          invited_by?: string | null
          joined_at?: string
        }
      }
      clients: {
        Row: {
          id: string
          workspace_id: string
          name: string
          slug: string
          logo_url: string | null
          website: string | null
          industry: string | null
          status: 'lead' | 'active' | 'paused' | 'churned'
          tier: 'basic' | 'standard' | 'premium' | 'enterprise'
          primary_color: string | null
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          name: string
          slug: string
          logo_url?: string | null
          website?: string | null
          industry?: string | null
          status?: 'lead' | 'active' | 'paused' | 'churned'
          tier?: 'basic' | 'standard' | 'premium' | 'enterprise'
          primary_color?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          name?: string
          slug?: string
          logo_url?: string | null
          website?: string | null
          industry?: string | null
          status?: 'lead' | 'active' | 'paused' | 'churned'
          tier?: 'basic' | 'standard' | 'premium' | 'enterprise'
          primary_color?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      client_contacts: {
        Row: {
          id: string
          client_id: string
          full_name: string
          email: string | null
          phone: string | null
          role: string | null
          is_primary: boolean
          created_at: string
        }
        Insert: {
          id?: string
          client_id: string
          full_name: string
          email?: string | null
          phone?: string | null
          role?: string | null
          is_primary?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          client_id?: string
          full_name?: string
          email?: string | null
          phone?: string | null
          role?: string | null
          is_primary?: boolean
          created_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          workspace_id: string
          client_id: string | null
          name: string
          slug: string
          description: string | null
          status: 'planning' | 'active' | 'paused' | 'completed' | 'cancelled'
          start_date: string | null
          end_date: string | null
          budget: number | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          client_id?: string | null
          name: string
          slug: string
          description?: string | null
          status?: 'planning' | 'active' | 'paused' | 'completed' | 'cancelled'
          start_date?: string | null
          end_date?: string | null
          budget?: number | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          client_id?: string | null
          name?: string
          slug?: string
          description?: string | null
          status?: 'planning' | 'active' | 'paused' | 'completed' | 'cancelled'
          start_date?: string | null
          end_date?: string | null
          budget?: number | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      invoices: {
        Row: {
          id: string
          workspace_id: string
          client_id: string
          project_id: string | null
          number: string
          title: string
          status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled'
          amount: number
          due_date: string | null
          paid_at: string | null
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          client_id: string
          project_id?: string | null
          number: string
          title: string
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled'
          amount?: number
          due_date?: string | null
          paid_at?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          client_id?: string
          project_id?: string | null
          number?: string
          title?: string
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled'
          amount?: number
          due_date?: string | null
          paid_at?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      workspace_invites: {
        Row: {
          id: string
          workspace_id: string
          email: string
          role: 'owner' | 'admin' | 'member' | 'viewer'
          token: string
          invited_by: string | null
          expires_at: string
          used_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          email: string
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          token?: string
          invited_by?: string | null
          expires_at?: string
          used_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          email?: string
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          token?: string
          invited_by?: string | null
          expires_at?: string
          used_at?: string | null
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          workspace_id: string
          user_id: string
          type: string
          title: string
          message: string | null
          read: boolean
          entity_type: string | null
          entity_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          user_id: string
          type: string
          title: string
          message?: string | null
          read?: boolean
          entity_type?: string | null
          entity_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          user_id?: string
          type?: string
          title?: string
          message?: string | null
          read?: boolean
          entity_type?: string | null
          entity_id?: string | null
          created_at?: string
        }
      }
      assets: {
        Row: {
          id: string
          workspace_id: string
          client_id: string | null
          name: string
          file_url: string
          storage_path: string
          file_type: string
          size: number
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          client_id?: string | null
          name: string
          file_url: string
          storage_path: string
          file_type: string
          size?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          client_id?: string | null
          name?: string
          file_url?: string
          storage_path?: string
          file_type?: string
          size?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      tasks: {
        Row: {
          id: string
          workspace_id: string
          project_id: string | null
          client_id: string | null
          title: string
          description: string | null
          status: 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'done'
          priority: 'low' | 'medium' | 'high' | 'urgent'
          assignee_id: string | null
          due_date: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          project_id?: string | null
          client_id?: string | null
          title: string
          description?: string | null
          status?: 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'done'
          priority?: 'low' | 'medium' | 'high' | 'urgent'
          assignee_id?: string | null
          due_date?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          project_id?: string | null
          client_id?: string | null
          title?: string
          description?: string | null
          status?: 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'done'
          priority?: 'low' | 'medium' | 'high' | 'urgent'
          assignee_id?: string | null
          due_date?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: {
      is_workspace_member: {
        Args: { ws_id: string }
        Returns: boolean
      }
      workspace_role: {
        Args: { ws_id: string }
        Returns: 'owner' | 'admin' | 'member' | 'viewer'
      }
    }
    Enums: {
      workspace_plan: 'free' | 'starter' | 'pro' | 'enterprise'
      member_role: 'owner' | 'admin' | 'member' | 'viewer'
      client_status: 'lead' | 'active' | 'paused' | 'churned'
      client_tier: 'basic' | 'standard' | 'premium' | 'enterprise'
      project_status: 'planning' | 'active' | 'paused' | 'completed' | 'cancelled'
      task_status: 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'done'
      task_priority: 'low' | 'medium' | 'high' | 'urgent'
      invoice_status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled'
    }
  }
}
