// Generated by Supabase CLI — regenerate with: npx supabase gen types typescript --local
// DO NOT EDIT MANUALLY

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          email: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          email: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          email?: string
          created_at?: string
          updated_at?: string
        }
      }
      workspaces: {
        Row: {
          id: string
          name: string
          slug: string
          logo_url: string | null
          plan: 'free' | 'starter' | 'pro' | 'enterprise'
          owner_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          logo_url?: string | null
          plan?: 'free' | 'starter' | 'pro' | 'enterprise'
          owner_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          logo_url?: string | null
          plan?: 'free' | 'starter' | 'pro' | 'enterprise'
          owner_id?: string
          created_at?: string
          updated_at?: string
        }
      }
      workspace_members: {
        Row: {
          id: string
          workspace_id: string
          user_id: string
          role: 'owner' | 'admin' | 'member' | 'viewer'
          invited_by: string | null
          joined_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          user_id: string
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          invited_by?: string | null
          joined_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          user_id?: string
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          invited_by?: string | null
          joined_at?: string
        }
      }
      clients: {
        Row: {
          id: string
          workspace_id: string
          name: string
          slug: string
          logo_url: string | null
          website: string | null
          industry: string | null
          status: 'lead' | 'active' | 'paused' | 'churned'
          tier: 'basic' | 'standard' | 'premium' | 'enterprise'
          primary_color: string | null
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          name: string
          slug: string
          logo_url?: string | null
          website?: string | null
          industry?: string | null
          status?: 'lead' | 'active' | 'paused' | 'churned'
          tier?: 'basic' | 'standard' | 'premium' | 'enterprise'
          primary_color?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          name?: string
          slug?: string
          logo_url?: string | null
          website?: string | null
          industry?: string | null
          status?: 'lead' | 'active' | 'paused' | 'churned'
          tier?: 'basic' | 'standard' | 'premium' | 'enterprise'
          primary_color?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      client_contacts: {
        Row: {
          id: string
          client_id: string
          full_name: string
          email: string | null
          phone: string | null
          role: string | null
          is_primary: boolean
          created_at: string
        }
        Insert: {
          id?: string
          client_id: string
          full_name: string
          email?: string | null
          phone?: string | null
          role?: string | null
          is_primary?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          client_id?: string
          full_name?: string
          email?: string | null
          phone?: string | null
          role?: string | null
          is_primary?: boolean
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: {
      is_workspace_member: {
        Args: { ws_id: string }
        Returns: boolean
      }
      workspace_role: {
        Args: { ws_id: string }
        Returns: 'owner' | 'admin' | 'member' | 'viewer'
      }
    }
    Enums: {
      workspace_plan: 'free' | 'starter' | 'pro' | 'enterprise'
      member_role: 'owner' | 'admin' | 'member' | 'viewer'
      client_status: 'lead' | 'active' | 'paused' | 'churned'
      client_tier: 'basic' | 'standard' | 'premium' | 'enterprise'
    }
  }
}
